FROM registry.access.redhat.com/ubi8/ubi-minimal
COPY bin/manager /bin/rte-operator
# bundle the operand, and use a backward compatible name for RTE
COPY bin/exporter /bin/resource-topology-exporter
RUN mkdir /etc/resource-topology-exporter/ && \
    touch /etc/resource-topology-exporter/config.yaml
RUN microdnf install pciutils
USER 65532:65532
ENTRYPOINT ["/bin/rte-operator"]
